### ISSUE TITLE
Add tip in console to install wallet-connect if you try to use connectAlgoWallet and dont have the lib installed via npm

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#2]

**Comment by spencercap** [comment]
never mind! we include this as a dependency. 

but perhaps algonaut.js should handle the checking of the local storage var `walletconnect` which that lib sets after a successful connect. that way algonaut and walletconnect can be in sync without having to make the project handle that. 

something like this?:

```typescript
const wcLocal = localStorage.getItem('walletconnect');
let savedState;
if (wcLocal) {
    savedState = JSON.parse(wcLocal);
    algonaut.account = savedState.accounts[0];
}
```

**Comment by enceladus** [comment]
@spencercap @youraerials @lanidelrey How elaborate do we want to get with our support of WalletConnect? It's kind of a lot for our small team to support. Is there anything wrong with providing minimal support (ie. ceasing development of WC features) and primarily telling people to use Inkey?

**Comment by spencercap** [comment]
i'm fine w this move – let's tell people to use inkey! 

when wallet connect v2 has an Algorand provider like it does for eth (https://docs.walletconnect.com/2.0/javascript/providers/ethereum) then we can revisit

**Comment by youraerials** [comment]
i'd like to keep minimal support and revisit when they have V2 up and running
... which i CANNOT BELIEVE is not done yet on the algo side it's like, such a blocker

**Comment by spencercap** [comment]
using `any-wallet` resolves this
