### ISSUE TITLE
why do i need an authenticated account when getting local state?

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#22]
https://github.com/thencc/algonautjs/blob/0ee18536ee35d5fab8cae3b7a1ca15f10fc5cff8/src/index.ts#L1428

**Comment by enceladus** [comment]
Ok spent a bit investigating this and I don't think it's a bug! I was able to run this just fine:

```js
let res = await algonaut.getAppLocalState(51066775, 'I4NYZQC342V5MIBDOCHZIIWED775F7NQCIAHWDRTGGAAAXNSYU7CBXZUQM');```

Although this gave me the error (rightly so, because it doesn't know what address to use):

```js
let res = await algonaut.getAppLocalState(51066775);
```

File again with specific code to reproduce if you think it's still an issue!
