### ISSUE TITLE
rename algonaut.js on npm (remove the dot ".")

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#24]
`npm i algonaut.js` -> `npm i algonautjs`

**Comment by enceladus** [comment]
we should create it as an alias (if possible) for backwards compatibility :)

**Comment by spencercap** [comment]
deprecate:
`npm deprecate algonaut.js@"<= 0.1.45" "WARNING: This project has been renamed to algonautjs. Install using algonautjs instead."`

to un-deprecate leave empty message:
`npm deprecate algonaut.js@"<= 0.1.45" ""`

---

new publish:
- update algonaut.js -> algonautjs in package.json + elsewhere 
- `npm publish --access public --tag beta --greater-version-only` 
- and publish "latest" tag too
- test if github actions still work
