### ISSUE TITLE
algonaut UI

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#33]
kit:
- [ ] single sign-on button (+ auth'd state w user identicon)
- [ ] txn status button (signed, submitted, confirmed)

**Comment by enceladus** [comment]
So I think this should be its own library (`npm install @thencc/algonaut-ui`), and furthermore, that UI should have its own framework integrations (`npm install @thencc/algonaut-vue`).

**Comment by spencercap** [comment]
> So I think this should be its own library (`npm install @thencc/algonaut-ui`), and furthermore, that UI should have its own framework integrations (`npm install @thencc/algonaut-vue`).

dope! like this a lot.

**Comment by spencercap** [comment]
these separate framework integrations should use [algo-identicons](https://github.com/thencc/algo-identicon) for the sign in btn's icon. 

something like this:
![image](https://user-images.githubusercontent.com/4987509/199798320-443f127c-e0c6-4fcf-8081-a7685adb1d0a.png)

**Comment by enceladus** [comment]
@spencercap can we publish algo-identicons to npm? :)

**Comment by spencercap** [comment]
yeah, but it's not ready yet 🙃
