### ISSUE TITLE
update config structure 

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#36]
```js
const algonaut = new Algonaut({
    BASE_SERVER: 'https://testnet-algorand.api.purestake.io/ps2',
    INDEX_SERVER: 'https://testnet-algorand.api.purestake.io/idx2',
    LEDGER: 'TestNet',
    PORT: '',
    API_TOKEN: { 'X-API-Key': process.env.API_TOKEN }
});
```
-->
```js
const algonaut = new Algonaut({
    BASE_SERVER: 'https://testnet-algorand.api.purestake.io/ps2',
    INDEX_SERVER: 'https://testnet-algorand.api.purestake.io/idx2',
    LEDGER: 'TestNet',
    PORT: '',
    API_TOKEN: process.env.API_TOKEN,
    API_TOKEN_HEADER: 'X-API-Key'
});
```

thoughts @enceladus ?

**Comment by enceladus** [comment]
This is definitely an improvement but I think we should maybe build this
into a bigger change.

It would be nice if you could load a testnet and mainnet server at once,
dynamically switching between them with a CURRENT_LEDGER parameter.

But it should also support loading one node that's completely "offline",
like a sandbox node that is neither testnet nor mainnet.

It'd be a big & breaking change to the configuration, though, and how Algod
is implemented, so let's give it some thought.

**Comment by spencercap** [comment]
k yes yes, makes sense. let's pike it
