### ISSUE TITLE
allow for algo/asset xfers of 0?

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#48]
currently atomicSendAlgo and sendAlgo methods disallow transfers of 0

do we want to support this? 
sometimes a 0 xfr is needed for an optin or rekeyto txn. should these be explicit methods or should we allow these to happen in the sendAlgo txn or both?

**Comment by enceladus** [comment]
I think we should support this if the network supports it!

**Comment by enceladus** [comment]
also: note to add this to unit tests #39
