### ISSUE TITLE
new Algonaut(config) takes any ole object

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#5]
we only use 3-4 fields in the config object, but a bunch of stuff **could** be in there. only take in what we care about + show warning / errors.

**Comment by spencercap** [comment]
added basics of this in 6897ee16216e23f11a4d54ee4efd25962a835902

`.isValidConfig()` can be updated with more checks

**Comment by enceladus** [comment]
There might be a benefit to not requiring node configuration at all — there are few offline utility functions in algonaut.

**Comment by spencercap** [comment]
true! i dont think the api is designed with this in mind so much. would you be open to changing it? for example, i provided `Buffer` as a separate export from algonaut a while back as a convenience for manipulating txns in ways our libs didnt yet support

**Comment by spencercap** [comment]
i can imagine algonaut to be a bit more typescript-y like vue or react where the primary export is a function like `useAlgonaut(config)` or `defineAlgonaut(config)` and you get a useable instance (that default Algonaut class we export now) into a specific algo chain based on the config. perhaps this approach is a bit more modern? there are performance + treeshaking benefits at scale.

the current way feels a bit like where threejs was before typescript. you'd do something like `import * as THREE from 'threejs` and all the functionality would be under `THREE` like `THREE.makeCircle(...)` or similar. what the ideal instantiation for algonaut? online/on-chain interactions as methods from this main class and offline ones as individual exports? open to chat this thru

**Comment by enceladus** [comment]
Hmm. I don't think we need to alter the API too much. Maybe we just put all
the offline methods together on a `utils` export:

```js
import utils from 'algonaut.js';
const signedTxns = utils.signTransactionGroup(txnArray);
```

These functions would be mirrored on any instance of the `Algonaut` class
as well, so you could also use `algonaut.signTransactionGroup` if you did
provide server config.

**Comment by enceladus** [comment]
Hmm. I don't think we need to alter the API too much. Maybe we just put all
the offline methods together on a `utils` export:

```js
import utils from 'algonaut.js';
const signedTxns = utils.signTransactionGroup(txnArray);
```

These functions would be mirrored on any instance of the `Algonaut` class as well, so you could also use `algonaut.signTransactionGroup` if you did provide server config.

**Comment by spencercap** [comment]
nice solution 🙏

keeps the current stuff working + adds modularity

**Comment by spencercap** [comment]
like this tho, right?
```ts
import { utils } from 'algonaut.js';
```

**Comment by enceladus** [comment]
That would make utils a property of the default export, the Algonaut class,
right?

**Comment by spencercap** [comment]
it makes `utils` `Algonaut` and `Buffer` (which should be moved into `utils` all peer exports

**Comment by spencercap** [comment]
btw we've been seeing some issues in the deno ts ctx using the default export... vscode's ts autocomplete and the runtime instance are misaligned somehow

**Comment by enceladus** [comment]
Currently we're doing

```js
import Algonaut from '@thencc/algonautjs'
```

**not**

```js
import { Algonaut } from '@thencc/algonautjs'
```

To be specific — the exports are `utils` `Buffer` and `default` (which, in the docs, we encourage naming `Algonaut`)

**Comment by enceladus** [comment]
Ok, done some work on this, see https://github.com/thencc/algonautjs/pull/37

**Comment by spencercap** [comment]
stale
