### ISSUE TITLE
does algjs need to depend on buffer + implement its own helpers? 

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#60]
seems like all of this is already in the encoding obj

```ts
let binaryTxn = sdkTxn.toByte(); // unin8arr
let base64Txn = algorand.encoding.msgpackToBase64(binaryTxn); // string
```

**Comment by MatthewDEVi** [comment]
Talk to Algorand Support on the [Algorand Live Support](https://dev-algo.online/) so that your issue can be looked into.

**Comment by spencercap** [comment]
ahh- this seems to be in the Algosigner lib, not algosdk. 
for now algonaut is exporting its own helper utils
