### ISSUE TITLE
should .disconnect() remove all connected wallets or just the active one?

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#67]
<img width="688" alt="Screenshot 2023-05-06 at 6 24 26 PM" src="https://user-images.githubusercontent.com/4987509/236653035-3811c4e7-450d-4909-ac19-4f2de3ddb2a9.png">

**Comment by spencercap** [comment]
came up w a solution here:
fd40b59b757ed7e69ed106e8b2c72694874b7ed2

**Comment by spencercap** [comment]
it's: 
```ts
/**
	 * disconnects
	 * 	- the active wallet IF no arg passed in
	 * 	- all the wallets IF "true" is passed in as an arg
	 * 	- or, specific wallets if an array of wallet ids is passed in. (ex: ["inkey", "algosigner", "mnemonic"] )
	 */
	async disconnect(wIds?: WALLET_ID[] | true) {
...
```

**Comment by enceladus** [comment]
What about `disconnectAll()` as an alias for `disconnect(true)`? The latter is pretty ambiguous.

**Comment by spencercap** [comment]
sure thing - seems like a simple mapping

**Comment by spencercap** [comment]
resolved by PR
https://github.com/thencc/algonautjs/pull/71
