### ISSUE TITLE
make algonaut js tests w mocha 

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#9]
hedera has a good example of this: 
https://github.com/hashgraph/hedera-sdk-js/blob/fc301d1bc0ede5a41a75f17c5407a11d93400ac2/packages/cryptography/package.json#L68-L72

**Comment by spencercap** [comment]
progess in:
- fc55f96437cd9928cab8145d43a91a05618800e4
- 980a8a1ce52b488246b1cb1863d7dc302a289ca9
- 6b9a38dfb3871117ba0dfc6dc04aff8d99b9b4c7
- dc1eebb89d1c5e77507d2da6b97395021e6b7ef0
- 24739e14d3e1bd8f8fe3b1b097e3cd1bff2664ee

**Comment by enceladus** [comment]
I think we're at a good starting point for testing. Closing this, make more specific issues for further tests.
